version: '3'
services:

  website:
    build: .
    image: waziup/website
    restart: unless-stopped
    ports:
      - 9000:9000
      - 81:81
    environment: 
      HUGO_BASE_URL: http://website.staging.waziup.io/
      WEBHOOK_SECRET:
      GIT_REPO_URL: https://github.com/Waziup/waziup.io-new.git 
      GIT_REPO_BRANCH: main
      GIT_REPO_CONTENT_PATH: .

volumes:
  html:
