version: '3'
services:

  webhooks:
    build: ./webhooks
    image: webhooks
    restart: unless-stopped
    container_name: webhooks
    volumes:
      - html:/target
      - ./data/webhooks/id_rsa:/ssh/id_rsa:ro
    environment: 
      HUGO_BASE_URL: https://lab.staging.waziup.io/
      WEBHOOK_SECRET:
      GIT_REPO_URL: git@github.com:Waziup/waziup.io-new.git
      GIT_REPO_BRANCH: main
      GIT_REPO_CONTENT_PATH: .

volumes:
  html: