version: '3'
services:
  website:
    build: .
    image: waziup/website
    ports:
      - 9000:9000
    environment: 
      HUGO_BASE_URL: http://website.staging.waziup.io/
      HUGO_PARAMS: --cleanDestinationDir
      HUGO_DESTINATION: /root/hugo-destination
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      WEBHOOK_PARAMS: -verbose
      GIT_URL: https://github.com/Waziup/waziup.io-new.git 
      GIT_BRANCH: main
      GIT_CONTENT_PATH: .
    volumes:
      - /var/www/website.staging.waziup.io:/root/hugo-destination
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size
